# Generated by Django 4.1.5 on 2023-05-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_time', models.DurationField()),
                ('exp', models.CharField(max_length=200)),
            ],
        ),
    ]
