# Generated by Django 4.1.5 on 2023-05-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='exp_time',
        ),
        migrations.AddField(
            model_name='experience',
            name='time',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
