# Generated by Django 4.1.5 on 2023-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_time',
            field=models.CharField(max_length=200),
        ),
    ]
