# Generated by Django 4.1.5 on 2023-05-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_person_photo_alter_education_school_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
